### ISSUE TITLE
WMS-0005 -  [Design] Welcome platform

### ISSUE THREAD

**Issue by Hienz** [Hienz/wms#5]
A sztori célja, hogy elkészüljön egy köszöntő felület, ami a még nem belépett (esetlegesen teljesen új) felhasználókat fogadja. 

**Todo**

- Alap design implementálása, felület elkészítése.
- A szöveges részeket egyelőre "Lorem ipsum"-mal kell kitölteni, ez majd a későbbiekben helyettesítve lesz.
- Regisztrációs és belépési input mezők implementálása, azok jól látható, megfelelő elhelyezése.
- Fontos, hogy a regisztráció és belépés felhasználónév - jelszó párossal működjön és ne raktárban gondolkodjunk.
-Form validációhoz további két osztály elkészítése (megfelelt és nem megfelelt), amit majd az angulár részleg hozzá tud rendelni az egyes inputokhoz. (pl. vörös keret ha nincs meg nyolc karakter, zöld ha megvan stb)

**Fejlesztői megjegyzés**

- Működnie még nem kell semminek, csak a design legyen meg, valamint hozzá egy üres controller.
- Az app.js-be kerüljön bele a state (akár lehet MainCtrl is).

**Comment by creativetribes** [comment]
A "Bejelentkezés" animációját az `accessPass` osztállyal tudod elindítani.
