### ISSUE TITLE
WMS-0007 - [Angular] Welcome platform

### ISSUE THREAD

**Issue by Hienz** [Hienz/wms#7]
A sztori célja a WMS-0005-ben elkészített beviteli felületek üzleti logikájának felépítése.

**Todo**

- Regisztrációs és belépési input mezők validálása.
- Regisztráció gomb összekötése backenddel a WMS-0006-ban leírt fájlok alapján.
- Belépés gomb összekötése backenddel a WMS-0006-ban leírt fájlok alapján.

**Validálási feltételek**

- REG: Minden mező kitöltése kötelező.
- REG: Felhasználónév minimum 8 karakter.
- REG: Jelszavak egyezzenek.
- REG: Jelszó minimum 8 karakter.
- REG: E-mail cím valid-e. (Tartalmaz @-ot, legalább egy pontot és a pont után maximum 4 karakter állhat.)
- LOG: Minden mező kitöltése kötelező.

**Comment by PatrikAGOD** [comment]
Valaki valami ötlet,hogy hogy számoljam meg a "."/dot után a hosszt?

**Comment by Hienz** [comment]
**A sztori elbukott a teszten a következő indokok miatt:**

- Nincs fent a validálás.
- Nincsenek fent az endpoint hívások.
